services:
  db:
    image: postgres:16
    container_name: moviereview-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MovieReviewDB
    ports:
      - "5433:5432"
    volumes:
      - moviereview_pgdata:/var/lib/postgresql/data

  api:
    image: moviereview-api
    container_name: moviereview-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5433;Database=MovieReviewDB;Username=postgres;Password=1234;Include Error Detail=true"

volumes:
  moviereview_pgdata:
